export const componentsStyles = {
  recentHistory: {
    wrapper: "mt-8",
    title: "text-sm font-semibold text-muted-foreground flex items-center gap-2 mb-4 uppercase tracking-wider",
    titleIcon: "w-4 h-4",
    listContainer: "flex gap-4 overflow-x-auto pb-4 custom-scrollbar",
    itemButton: "group shrink-0 w-64 text-left space-y-2 cursor-pointer",
    imageWrapper: "relative aspect-video rounded-md overflow-hidden border border-border",
    image: "w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity",
    playOverlay: "absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-background/20 backdrop-blur-[2px]",
    playButton: "bg-background/80 p-2 rounded-full shadow-sm",
    playIcon: "w-4 h-4 text-primary",
    languageBadge: "absolute top-2 right-2 bg-background/90 text-foreground px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider shadow-sm border border-border",
    itemTitle: "text-sm font-medium text-foreground line-clamp-2 leading-snug group-hover:text-primary transition-colors"
  },
  videoInput: {
    wrapper: "w-full",
    form: "relative z-10",
    inputGroup: "flex flex-col sm:flex-row gap-4 items-stretch",
    inputWrapper: "relative grow",
    input: "w-full bg-card px-4 md:px-5 py-3 md:py-4 text-sm md:text-base text-foreground placeholder:text-muted-foreground outline-none border border-border focus:border-primary transition-colors rounded-lg shadow-sm",
    submitButton: "px-6 md:px-8 bg-primary hover:bg-primary/90 text-primary-foreground font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap flex items-center justify-center gap-2 cursor-pointer active:scale-[0.98] rounded-lg border border-transparent shadow-sm text-sm md:text-base",
    spinner: "w-4 h-4 md:w-5 md:h-5 animate-spin",
    footer: "flex flex-col sm:flex-row justify-between items-start sm:items-center mt-3 gap-2",
    helperText: "text-xs md:text-sm text-muted-foreground",
    languageGroup: "flex items-center gap-2 text-xs md:text-sm text-muted-foreground",
    languageLabel: "font-medium",
    languageSelect: "bg-transparent text-foreground outline-none cursor-pointer hover:text-primary transition-colors font-medium border-b border-dashed border-border pb-0.5"
  },
  videoInfoCard: {
    wrapper: "w-full flex flex-col gap-8",
    header: "w-full flex flex-col md:flex-row gap-6 items-start md:items-end justify-between pb-6 border-b border-border",
    metaWrapper: "space-y-4 max-w-3xl",
    metaTagsGroup: "flex items-center gap-3 flex-wrap",
    languageBadge: "bg-primary/10 text-primary text-[10px] md:text-xs px-2.5 py-1 rounded-sm font-bold uppercase tracking-widest border border-primary/20",
    durationBadge: "bg-muted text-foreground text-[10px] md:text-xs px-2.5 py-1 rounded-sm font-medium border border-border",
    dateText: "text-muted-foreground text-xs md:text-sm font-mono flex items-center gap-1",
    title: "text-2xl md:text-4xl font-semibold tracking-tight text-foreground leading-tight",
    channelText: "text-muted-foreground font-mono text-xs md:text-sm",
    actionsGroup: "flex flex-wrap items-center gap-2 shrink-0 w-full md:w-auto",
    shareButton: "bg-secondary text-secondary-foreground hover:bg-secondary/80 px-4 py-2 rounded-md font-medium flex items-center gap-2 transition-colors text-xs md:text-sm shadow-sm border border-border",
    watchButton: "bg-foreground text-background hover:bg-foreground/90 px-4 py-2 rounded-md font-medium flex items-center gap-2 transition-colors text-xs md:text-sm shadow-sm",
    contentWrapper: "flex flex-col gap-8",
    sectionHeader: "flex justify-between items-center mb-4",
    sectionTitle: "text-lg font-semibold text-foreground",
    sectionTitleWithIcon: "text-lg font-semibold mb-4 text-foreground flex items-center gap-2",
    sectionIcon: "w-5 h-5 text-primary",
    copyButton: "p-2 hover:bg-muted rounded-md transition-colors text-muted-foreground hover:text-foreground",
    summaryText: "text-foreground/90 text-sm md:text-base leading-relaxed whitespace-pre-wrap bg-card p-6 rounded-lg border border-border",
    insightsGrid: "grid grid-cols-1 gap-3",
    insightItem: "flex gap-4 p-4 rounded-lg bg-card border border-border",
    insightNumber: "shrink-0 w-6 h-6 rounded bg-primary/10 flex items-center justify-center text-primary font-mono text-xs",
    insightText: "text-foreground/90 text-sm md:text-base leading-relaxed",
    topicsGroup: "flex flex-wrap gap-2",
    topicButtonBase: "bg-card text-foreground text-xs md:text-sm px-3 py-1.5 rounded-md font-medium border border-border flex items-center gap-2 group/topic",
    topicButtonHover: "hover:bg-muted hover:border-primary/50 transition-colors cursor-pointer",
    topicButtonDisabled: "opacity-70 cursor-default",
    topicHash: "text-muted-foreground font-mono",
    topicTimestamp: "text-[10px] text-muted-foreground font-mono opacity-80",
    topicsEmpty: "text-muted-foreground text-sm italic"
  },
  transcriptCard: {
    wrapper: "bg-card text-card-foreground shadow-sm rounded-lg border border-border flex flex-col h-[600px]",
    header: "sticky top-0 z-10 bg-card border-b border-border px-4 md:px-6 py-4 flex justify-between items-center shrink-0",
    headerTitleContainer: "flex items-center gap-2 md:gap-3",
    headerTitle: "text-sm md:text-base font-semibold uppercase tracking-widest text-muted-foreground",
    headerActionsContainer: "flex items-center gap-2 md:gap-3",
    searchInputWrapper: "relative group",
    searchInput: "pl-3 md:pl-4 pr-3 md:pr-4 py-1.5 md:py-2 text-xs md:text-sm rounded-lg border border-border bg-background/50 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/50 text-foreground w-24 md:w-32 md:focus:w-48 transition-all placeholder:text-muted-foreground/50",
    highlightModeBtnBase: "p-1.5 md:p-2 rounded-lg border transition-all cursor-pointer",
    highlightModeBtnActive: "bg-yellow-500/10 border-yellow-500/50 text-yellow-600 dark:text-yellow-400",
    highlightModeBtnInactive: "border-border bg-background/50 text-muted-foreground hover:bg-muted hover:text-foreground",
    highlightIcon: "w-3.5 h-3.5 md:w-4 md:h-4",
    contentWrapper: "grow overflow-hidden flex flex-col min-h-0",
    scrollContainer: "grow overflow-y-auto custom-scrollbar p-4 md:p-6 space-y-1",
    segmentRow: "group md:p-2 hover:bg-muted rounded-md flex gap-4 transition-colors",
    timestampBtn: "text-muted-foreground group-hover:text-primary font-mono text-xs pt-1 text-right transition-colors font-medium opacity-80 cursor-pointer",
    segmentTextContainer: "grow text-foreground/90 leading-relaxed pr-8 relative text-sm md:text-base",
    highlightedText: "bg-yellow-200 dark:bg-yellow-700 text-gray-900 dark:text-gray-100 rounded-sm px-0.5",
    copySegmentBtn: "absolute right-0 top-0 p-1 opacity-0 group-hover:opacity-100 transition-opacity text-muted-foreground hover:text-foreground cursor-pointer",
    copySegmentIcon: "w-3.5 h-3.5",
    emptyStateContainer: "h-full flex flex-col items-center justify-center text-muted-foreground p-10 opacity-60",
    footer: "bg-card border-t border-border px-4 md:px-6 py-4 flex flex-col sm:flex-row justify-between items-center text-sm gap-4 shrink-0",
    footerText: "text-muted-foreground font-mono text-xs",
    paginationContainer: "flex items-center gap-2",
    paginationBtn: "p-2 rounded-lg border border-border text-muted-foreground hover:bg-primary/10 hover:text-primary hover:border-primary/20 disabled:opacity-30 disabled:pointer-events-none transition-all",
    paginationIcon: "w-4 h-4",
    divider: "h-6 w-px bg-border mx-2",
    exportGroup: "flex bg-muted rounded-lg overflow-hidden border border-border",
    exportBtnBase: "px-3 py-2 text-muted-foreground hover:text-foreground hover:bg-background transition-all font-medium text-xs uppercase tracking-wide cursor-pointer flex items-center gap-2",
    exportBtnLeft: "border-r border-border",
    exportIconBase: "w-3.5 h-3.5",
    exportIconSuccess: "w-3.5 h-3.5 text-emerald-500"
  }
} as const;
