/**
 * VideoInfoCard Component.
 * Displays the core results: Title, AI Summary, Actionable Insights, and Key Topics.
 */
import { Download, Youtube, Copy, Check, FileText, Lightbulb, Play } from "lucide-react";
import { useState, RefObject } from "react";
import { VideoAnalysisResult } from "@/types";
import { formatDuration, formatDate } from "@/lib/utils";
import { Player, PlayerHandle } from "./Player";

interface VideoInfoCardProps {
    data: VideoAnalysisResult;
    playerRef: RefObject<PlayerHandle | null>;
    onSeek: (seconds: number) => void;
}

const parseTimestamp = (ts: string): number => {
    if (!ts || typeof ts !== 'string') return 0;
    const parts = ts.split(':').map(Number);
    if (parts.length === 2) return parts[0] * 60 + parts[1];
    if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
    return 0;
};

export function VideoInfoCard({ data, playerRef, onSeek }: VideoInfoCardProps) {
    const { metadata, summary, key_topics, actionable_insights, video_id, language } = data;
    const [copiedSummary, setCopiedSummary] = useState(false);

    const title = data.title || metadata.title || "Untitled Video";
    const thumbnail =
        metadata.thumbnail?.replace("default.jpg", "maxresdefault.jpg") ||
        `https://img.youtube.com/vi/${video_id}/maxresdefault.jpg`;

    const handleCopySummary = () => {
        navigator.clipboard.writeText(summary);
        setCopiedSummary(true);
        setTimeout(() => setCopiedSummary(false), 2000);
    };

    const handleDownload = (format: 'txt' | 'md') => {
        /**
         * Simple file generation logic:
         * 1. Creates a string with the summary data.
         * 2. Turns that string into a 'Blob' (Binary Large Object).
         * 3. Creates a temporary URL for that blob and triggers a browser download.
         */
        const topicList =
            key_topics && key_topics.length > 0
                ? key_topics.map(t => `- ${t}`).join("\n")
                : "No key topics identified";

        const insightsList =
            actionable_insights && actionable_insights.length > 0
                ? actionable_insights.map(i => `- ${i}`).join("\n")
                : "No insights generated";

        let content = "";

        if (format === 'md') {
            content = `# ${title}\n\n` +
                `> [Watch on YouTube](https://youtu.be/${video_id})\n\n` +
                `## Executive Summary\n${summary}\n\n` +
                `## Key Topics\n${topicList}\n\n` +
                `## Actionable Insights\n${insightsList}\n\n` +
                `--- \n*Generated by VidScribe*`;
        } else {
            content = `YouTube Video Summary\n\nTitle: ${title}\nVideo ID: ${video_id}\n\nSummary:\n${summary}\n\nKey Topics:\n${topicList}\n\nActionable Insights:\n${insightsList}`;
        }

        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `summary-${video_id}.${format}`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="bg-card text-card-foreground shadow-xl rounded-2xl border border-border/50 overflow-hidden transition-all hover:shadow-2xl">
            <div className="relative w-full overflow-hidden group">
                {/* Background Blur Image */}
                <div
                    className="absolute inset-0 bg-cover bg-center blur-3xl opacity-50 dark:opacity-30 scale-110"
                    style={{ backgroundImage: `url(${thumbnail})` }}
                />
                <div className="absolute inset-0 bg-linear-to-t from-background via-background/60 to-transparent" />

                <div className="relative p-5 md:py-9 md:px-8 w-full z-10 flex flex-col md:flex-row gap-6 items-start md:items-end justify-between">
                    <div className="space-y-3 max-w-2xl">
                        <div className="flex items-center gap-3 flex-wrap">
                            <span className="bg-primary/90 text-primary-foreground text-[10px] md:text-xs px-2 md:px-2.5 py-1 rounded-full font-bold uppercase tracking-wide shadow-lg backdrop-blur-md">
                                {language}
                            </span>
                            <span className="bg-black/60 text-white text-[10px] md:text-xs px-2 md:px-2.5 py-1 rounded-full font-medium backdrop-blur-md border border-white/10">
                                {metadata.duration ? formatDuration(metadata.duration) : 'N/A'}
                            </span>
                            <span className="text-foreground/60 dark:text-white/80 text-xs md:text-sm font-medium flex items-center gap-1">
                                {formatDate(metadata.published_at)}
                            </span>
                        </div>
                        <h2 className="text-xl md:text-4xl font-bold tracking-tight text-foreground dark:text-white leading-tight drop-shadow-sm dark:drop-shadow-lg">
                            {title}
                        </h2>
                        <p className="text-foreground/80 dark:text-white/90 font-medium text-sm md:text-lg">
                            {metadata.channel || "Unknown Channel"}
                        </p>
                    </div>

                    <div className="flex items-center gap-2 md:gap-3 shrink-0 w-full md:w-auto">
                        <div className="flex bg-emerald-600 rounded-xl overflow-hidden shadow-lg hover:shadow-emerald-600/40 hover:-translate-y-0.5 transition-all">
                            <button
                                onClick={() => handleDownload('txt')}
                                className="px-3 py-2 md:px-4 md:py-2.5 text-white font-semibold flex items-center gap-2 hover:bg-emerald-700 transition-colors border-r border-white/10 text-xs md:text-base cursor-pointer"
                                title="Download as TXT"
                            >
                                <Download className="w-4 h-4 md:w-5 md:h-5" /> Save
                            </button>
                            <button
                                onClick={() => handleDownload('md')}
                                className="px-2 py-2 md:px-3 md:py-2.5 text-white font-semibold flex items-center gap-2 hover:bg-emerald-700 transition-colors cursor-pointer"
                                title="Download as Markdown"
                            >
                                <FileText className="w-4 h-4 md:w-5 md:h-5" />
                            </button>
                        </div>
                        <a
                            href={`https://youtu.be/${video_id}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 md:px-5 md:py-2.5 rounded-xl font-semibold flex items-center gap-2 transition-all shadow-lg hover:shadow-red-600/40 hover:-translate-y-0.5 text-xs md:text-base"
                        >
                            <Youtube className="w-4 h-4 md:w-5 md:h-5" /> Watch
                        </a>
                    </div>
                </div>
            </div>

            <div className="p-3 md:p-8 grid grid-cols-1 lg:grid-cols-3 gap-12">
                <div className="lg:col-span-2 space-y-10">
                    <section>
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-xl font-semibold flex items-center gap-2 text-primary">
                                <div className="w-1.5 h-6 bg-primary rounded-full" />
                                Executive Summary
                            </h3>
                            <button
                                onClick={handleCopySummary}
                                className="p-2 hover:bg-muted rounded-lg transition-all text-muted-foreground hover:text-foreground border border-transparent hover:border-border"
                                title="Copy Summary"
                            >
                                {copiedSummary ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                            </button>
                        </div>
                        <div className="text-foreground/90 text-xs md:text-base leading-8 whitespace-pre-wrap bg-muted/30 p-4 md:p-6 rounded-2xl border border-border/50 shadow-inner group relative">
                            {summary || "No summary available."}
                        </div>
                    </section>

                    {actionable_insights && actionable_insights.length > 0 && (
                        <section>
                            <h3 className="text-xl font-semibold mb-4 flex items-center gap-2 text-emerald-600 dark:text-emerald-400">
                                <Lightbulb className="w-6 h-6" />
                                Actionable Insights
                            </h3>
                            <div className="grid grid-cols-1 gap-3">
                                {actionable_insights.map((insight, index) => (
                                    <div key={index} className="flex gap-4 p-4 rounded-xl bg-emerald-500/5 border border-emerald-500/10 hover:border-emerald-500/30 transition-all">
                                        <div className="shrink-0 w-6 h-6 rounded-full bg-emerald-500/20 flex items-center justify-center text-emerald-600 dark:text-emerald-400 font-bold text-xs mt-0.5">
                                            {index + 1}
                                        </div>
                                        <p className="text-foreground/80 text-sm md:text-base leading-relaxed italic">
                                            {insight}
                                        </p>
                                    </div>
                                ))}
                            </div>
                        </section>
                    )}

                    <section>
                        <h3 className="text-xl font-semibold mb-4 flex items-center gap-2 text-foreground/80">
                            <div className="w-1.5 h-6 bg-muted-foreground/30 rounded-full" />
                            Key Topics
                        </h3>
                        <div className="flex flex-wrap gap-3">
                            {key_topics?.length > 0 ? (
                                key_topics.map((topicData, index) => {
                                    const topic = typeof topicData === 'string' ? topicData : topicData?.topic;
                                    const timestamp = typeof topicData === 'object' ? topicData?.timestamp : null;

                                    return (
                                        <button
                                            key={index}
                                            onClick={() => timestamp && onSeek(parseTimestamp(timestamp))}
                                            disabled={!timestamp}
                                            className={`bg-primary/5 text-foreground/90 text-xs md:text-sm px-2 md:px-4 py-2 rounded-xl font-semibold transition-all border border-primary/10 shadow-sm flex items-center gap-2 group/topic ${timestamp
                                                ? "hover:bg-primary/15 hover:border-primary/30 hover:-translate-y-0.5 hover:shadow-md"
                                                : "opacity-60 cursor-default"
                                                }`}
                                        >
                                            <span className="text-primary font-bold group-hover/topic:scale-110 transition-transform">#</span>
                                            <span>{topic}</span>
                                            {timestamp && (
                                                <span className="text-[10px] md:text-xs bg-muted px-1.5 py-0.5 rounded-md font-mono opacity-60 group-hover/topic:opacity-100 transition-opacity">
                                                    {timestamp}
                                                </span>
                                            )}
                                            {timestamp && <Play className="w-3 h-3 opacity-0 group-hover/topic:opacity-100 transition-opacity text-primary" />}
                                        </button>
                                    );
                                })
                            ) : (
                                <span className="text-muted-foreground text-sm italic">No key topics identified</span>
                            )}
                        </div>
                    </section>
                </div>

                <div className="space-y-8">
                    {metadata.is_embeddable ? (
                        <div className="space-y-4" id="interactive-player">
                            <h4 className="text-sm font-bold uppercase tracking-widest text-muted-foreground font-mono flex items-center gap-2">
                                <div className="w-1 h-3 bg-primary rounded-full" />
                                Interactive Player
                            </h4>
                            <Player videoId={video_id} ref={playerRef} />
                        </div>
                    ) : (
                        <a
                            href={`https://youtu.be/${video_id}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="block bg-muted/20 rounded-2xl p-3 md:p-4 border border-border/50 aspect-video relative group overflow-hidden shadow-2xl hover:border-primary/30 transition-colors"
                        >
                            <img
                                src={thumbnail}
                                alt="Thumbnail"
                                className="w-full h-full object-cover rounded-xl opacity-90 group-hover:opacity-100 transition-all duration-500"
                            />
                            <div className="absolute inset-0 flex items-center justify-center">
                                <div className="bg-black/60 p-2 md:p-4 rounded-full backdrop-blur-md group-hover:scale-110 transition-all duration-300 shadow-xl border border-white/10">
                                    <svg
                                        viewBox="0 0 24 24"
                                        className="w-5 h-5 md:w-10 md:h-10 text-[#FF0000] fill-current"
                                        xmlns="http://www.w3.org/2000/svg"
                                    >
                                        <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z" />
                                    </svg>
                                </div>
                            </div>
                        </a>
                    )}

                    <div className="p-4 md:p-6 bg-primary/5 rounded-2xl border border-primary/10">
                        <h4 className="text-sm font-bold uppercase tracking-widest text-primary mb-3">Video Stats</h4>
                        <div className="space-y-3">
                            <div className="flex justify-between text-sm">
                                <span className="text-muted-foreground">Language</span>
                                <span className="font-semibold">{language}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                                <span className="text-muted-foreground">Duration</span>
                                <span className="font-semibold">{metadata.duration ? formatDuration(metadata.duration) : 'N/A'}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                                <span className="text-muted-foreground">Published</span>
                                <span className="font-semibold">{formatDate(metadata.published_at)}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
