/**
 * VideoInfoCard Component.
 * Displays the core results: Title, AI Summary, Actionable Insights, and Key Topics.
 */
import { Download, Youtube, Copy, Check, FileText, Lightbulb, Play } from "lucide-react";
import { useState, RefObject } from "react";
import { VideoAnalysisResult } from "@/types";
import { formatDuration, formatDate } from "@/lib/utils";
import { Player, PlayerHandle } from "./Player";

interface VideoInfoCardProps {
    data: VideoAnalysisResult;
    playerRef: RefObject<PlayerHandle | null>;
    onSeek: (seconds: number) => void;
}

const parseTimestamp = (ts: string): number => {
    if (!ts || typeof ts !== 'string') return 0;
    const parts = ts.split(':').map(Number);
    if (parts.length === 2) return parts[0] * 60 + parts[1];
    if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
    return 0;
};

export function VideoInfoCard({ data, playerRef, onSeek }: VideoInfoCardProps) {
    const { metadata, summary, key_topics, actionable_insights, video_id, language } = data;
    const [copiedSummary, setCopiedSummary] = useState(false);

    const title = data.title || metadata.title || "Untitled Video";
    const thumbnail =
        metadata.thumbnail?.replace("default.jpg", "maxresdefault.jpg") ||
        `https://img.youtube.com/vi/${video_id}/maxresdefault.jpg`;

    const handleCopySummary = () => {
        navigator.clipboard.writeText(summary);
        setCopiedSummary(true);
        setTimeout(() => setCopiedSummary(false), 2000);
    };

    const handleDownload = (format: 'txt' | 'md') => {
        /**
         * Simple file generation logic:
         * 1. Creates a string with the summary data.
         * 2. Turns that string into a 'Blob' (Binary Large Object).
         * 3. Creates a temporary URL for that blob and triggers a browser download.
         */
        const topicList =
            key_topics && key_topics.length > 0
                ? key_topics.map(t => `- ${t}`).join("\n")
                : "No key topics identified";

        const insightsList =
            actionable_insights && actionable_insights.length > 0
                ? actionable_insights.map(i => `- ${i}`).join("\n")
                : "No insights generated";

        let content = "";

        if (format === 'md') {
            content = `# ${title}\n\n` +
                `> [Watch on YouTube](https://youtu.be/${video_id})\n\n` +
                `## Executive Summary\n${summary}\n\n` +
                `## Key Topics\n${topicList}\n\n` +
                `## Actionable Insights\n${insightsList}\n\n` +
                `--- \n*Generated by VidScribe*`;
        } else {
            content = `YouTube Video Summary\n\nTitle: ${title}\nVideo ID: ${video_id}\n\nSummary:\n${summary}\n\nKey Topics:\n${topicList}\n\nActionable Insights:\n${insightsList}`;
        }

        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `summary-${video_id}.${format}`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="w-full flex flex-col gap-8">
            <div className="w-full flex flex-col md:flex-row gap-6 items-start md:items-end justify-between pb-6 border-b border-border">
                <div className="space-y-4 max-w-3xl">
                    <div className="flex items-center gap-3 flex-wrap">
                        <span className="bg-primary/10 text-primary text-[10px] md:text-xs px-2.5 py-1 rounded-sm font-bold uppercase tracking-widest border border-primary/20">
                            {language}
                        </span>
                        <span className="bg-muted text-foreground text-[10px] md:text-xs px-2.5 py-1 rounded-sm font-medium border border-border">
                            {metadata.duration ? formatDuration(metadata.duration) : 'N/A'}
                        </span>
                        <span className="text-muted-foreground text-xs md:text-sm font-mono flex items-center gap-1">
                            {formatDate(metadata.published_at)}
                        </span>
                    </div>
                    <h2 className="text-2xl md:text-4xl font-semibold tracking-tight text-foreground leading-tight">
                        {title}
                    </h2>
                    <p className="text-muted-foreground font-mono text-xs md:text-sm">
                        {metadata.channel || "Unknown Channel"}
                    </p>
                </div>

                <div className="flex flex-wrap items-center gap-2 shrink-0 w-full md:w-auto">
                    <div className="flex rounded-md overflow-hidden border border-border shadow-sm">
                        <button
                            onClick={() => handleDownload('txt')}
                            className="px-3 py-2 bg-card hover:bg-muted text-foreground font-medium flex items-center gap-2 transition-colors border-r border-border text-xs md:text-sm cursor-pointer"
                            title="Download as TXT"
                        >
                            <Download className="w-4 h-4" /> Save TXT
                        </button>
                        <button
                            onClick={() => handleDownload('md')}
                            className="px-3 py-2 bg-card hover:bg-muted text-foreground font-medium flex items-center gap-2 transition-colors cursor-pointer text-xs md:text-sm"
                            title="Download as Markdown"
                        >
                            <FileText className="w-4 h-4" /> MD
                        </button>
                    </div>
                    <a
                        href={`https://youtu.be/${video_id}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="bg-foreground text-background hover:bg-foreground/90 px-4 py-2 rounded-md font-medium flex items-center gap-2 transition-colors text-xs md:text-sm shadow-sm"
                    >
                        <Youtube className="w-4 h-4" /> Watch
                    </a>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                <div className="lg:col-span-8 flex flex-col gap-8">
                    <section>
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-lg font-semibold text-foreground">
                                Executive Summary
                            </h3>
                            <button
                                onClick={handleCopySummary}
                                className="p-2 hover:bg-muted rounded-md transition-colors text-muted-foreground hover:text-foreground"
                                title="Copy Summary"
                            >
                                {copiedSummary ? <Check className="w-4 h-4 text-primary" /> : <Copy className="w-4 h-4" />}
                            </button>
                        </div>
                        <div className="text-foreground/90 text-sm md:text-base leading-relaxed whitespace-pre-wrap bg-card p-6 rounded-lg border border-border">
                            {summary || "No summary available."}
                        </div>
                    </section>

                    {actionable_insights && actionable_insights.length > 0 && (
                        <section>
                            <h3 className="text-lg font-semibold mb-4 text-foreground flex items-center gap-2">
                                <Lightbulb className="w-5 h-5 text-primary" />
                                Actionable Insights
                            </h3>
                            <div className="grid grid-cols-1 gap-3">
                                {actionable_insights.map((insight, index) => (
                                    <div key={index} className="flex gap-4 p-4 rounded-lg bg-card border border-border">
                                        <div className="shrink-0 w-6 h-6 rounded bg-primary/10 flex items-center justify-center text-primary font-mono text-xs">
                                            {index + 1}
                                        </div>
                                        <p className="text-foreground/90 text-sm md:text-base leading-relaxed">
                                            {insight}
                                        </p>
                                    </div>
                                ))}
                            </div>
                        </section>
                    )}

                    <section>
                        <h3 className="text-lg font-semibold mb-4 text-foreground">
                            Key Topics
                        </h3>
                        <div className="flex flex-wrap gap-2">
                            {key_topics?.length > 0 ? (
                                key_topics.map((topicData, index) => {
                                    const topic = typeof topicData === 'string' ? topicData : topicData?.topic;
                                    const timestamp = typeof topicData === 'object' ? topicData?.timestamp : null;

                                    return (
                                        <button
                                            key={index}
                                            onClick={() => timestamp && onSeek(parseTimestamp(timestamp))}
                                            disabled={!timestamp}
                                            className={`bg-card text-foreground text-xs md:text-sm px-3 py-1.5 rounded-md font-medium border border-border flex items-center gap-2 group/topic ${timestamp
                                                ? "hover:bg-muted hover:border-primary/50 transition-colors cursor-pointer"
                                                : "opacity-70 cursor-default"
                                                }`}
                                        >
                                            <span className="text-muted-foreground font-mono">#</span>
                                            <span>{topic}</span>
                                            {timestamp && (
                                                <span className="text-[10px] text-muted-foreground font-mono opacity-80">
                                                    {timestamp}
                                                </span>
                                            )}
                                        </button>
                                    );
                                })
                            ) : (
                                <span className="text-muted-foreground text-sm italic">No key topics identified</span>
                            )}
                        </div>
                    </section>
                </div>

                <div className="lg:col-span-4 flex flex-col gap-6">
                    {metadata.is_embeddable ? (
                        <div className="space-y-4" id="interactive-player">
                            <h4 className="text-xs font-mono uppercase tracking-widest text-muted-foreground">
                                Interactive Player
                            </h4>
                            <div className="rounded-lg overflow-hidden border border-border bg-card">
                                <Player videoId={video_id} ref={playerRef} />
                            </div>
                        </div>
                    ) : (
                        <a
                            href={`https://youtu.be/${video_id}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="block rounded-lg border border-border aspect-video relative group overflow-hidden"
                        >
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img
                                src={thumbnail}
                                alt="Thumbnail"
                                className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity duration-300"
                            />
                            <div className="absolute inset-0 flex items-center justify-center">
                                <div className="bg-background/80 p-3 rounded-md backdrop-blur-sm border border-border shadow-sm">
                                    <Play className="w-6 h-6 text-foreground" fill="currentColor" />
                                </div>
                            </div>
                        </a>
                    )}

                    <div className="p-5 bg-card rounded-lg border border-border space-y-4">
                        <h4 className="text-xs font-mono uppercase tracking-widest text-muted-foreground">Video Stats</h4>
                        <div className="space-y-2">
                            <div className="flex justify-between text-sm">
                                <span className="text-muted-foreground">Language</span>
                                <span className="font-medium text-foreground">{language}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                                <span className="text-muted-foreground">Duration</span>
                                <span className="font-medium text-foreground">{metadata.duration ? formatDuration(metadata.duration) : 'N/A'}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                                <span className="text-muted-foreground">Published</span>
                                <span className="font-medium text-foreground">{formatDate(metadata.published_at)}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
